// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhAzyNU8Q5euoMpKE59l4m_jbP60JMpvA',
    appId: '1:516049197910:web:2bf5a020ef4e71aa3694f7',
    messagingSenderId: '516049197910',
    projectId: 'coffee-shop-86dbc',
    authDomain: 'coffee-shop-86dbc.firebaseapp.com',
    storageBucket: 'coffee-shop-86dbc.appspot.com',
    measurementId: 'G-CVCRQ9W2B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChf3SeC_H2V4UE3F2E4pFkvGaYzxF0ENY',
    appId: '1:516049197910:android:582858a8b4c8a17b3694f7',
    messagingSenderId: '516049197910',
    projectId: 'coffee-shop-86dbc',
    storageBucket: 'coffee-shop-86dbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv9j07Ijnwmx87WqGBQhgTk-yq57M8OwM',
    appId: '1:516049197910:ios:ce3d0d5d96eb70a43694f7',
    messagingSenderId: '516049197910',
    projectId: 'coffee-shop-86dbc',
    storageBucket: 'coffee-shop-86dbc.appspot.com',
    iosBundleId: 'com.example.coffeeshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv9j07Ijnwmx87WqGBQhgTk-yq57M8OwM',
    appId: '1:516049197910:ios:ce3d0d5d96eb70a43694f7',
    messagingSenderId: '516049197910',
    projectId: 'coffee-shop-86dbc',
    storageBucket: 'coffee-shop-86dbc.appspot.com',
    iosBundleId: 'com.example.coffeeshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhAzyNU8Q5euoMpKE59l4m_jbP60JMpvA',
    appId: '1:516049197910:web:ec14fc85d7be62c83694f7',
    messagingSenderId: '516049197910',
    projectId: 'coffee-shop-86dbc',
    authDomain: 'coffee-shop-86dbc.firebaseapp.com',
    storageBucket: 'coffee-shop-86dbc.appspot.com',
    measurementId: 'G-B0454EV8VJ',
  );
}
